music/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'music'
urlpatterns = [
	# /music/ 
    url(r'^$', views.index, name='index'),

    # /music/id/
    url(r'^(?P<album_id>[0-9]+)/$',views.detail, name='detail'),

    # /music/<album_id>/favorite/
    
    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name='favorite'),


]

myapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)
	
	def __str__(self):
		return self.album_title +  '	-	' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	song_title = models.CharField(max_length=250)
	file_type = models.CharField(max_length=10)
	favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from .models import Album,Song



def index(request):
	#Cogemos todos los albumos de la base de datos
	all_albums = Album.objects.all()
	#Realizamos un context con los datos para poder mostrarlos en la vista con un for
	context = { 'all_albums': all_albums}
	return render(request,'index.html',context)

def detail(request,album_id):
	album = get_object_or_404(Album.objects, id=album_id)
	return render(request,'details.html',{'album': album})


def favorite(request,album_id):
	album = get_object_or_404(Album.objects, id=album_id)
	try:
		selected_song = album.song_set.get(id=request.POST['song'])
	except (KeyError, Song.DoesNotExist):
		return render(request,'details.html',{
				'album': album,
				'error_message': "Tried to favorite, but something gone wrong",
			})
	else:
		selected_song.favorite = not  selected_song.favorite
		selected_song.save()
		return render(request,'details.html',{'album': album})

music/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Loads the patch to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <title>{% block title %} App django Index{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<!-- nav --> 
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- nav-bar header -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"> </span>
            <span class="icon-bar"> </span>
            <span class="icon-bar"> </span>
        </button>
         <a class="navbar-brand" href="{% url 'music:index' %}">Sergio Djanger</a>
    </div>
    <!-- ./nav-bar header -->
    <!-- items --> 
    <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav"> 
            <li class=""> 
                <a href="{% url 'music:index' %}"> 
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"> </span> Albums
                </a>
            </li> 
            <li class=""> 
                <a href="#"> 
                    <span class="glyphicon glyphicon-music" aria-hidden="true"> </span> Songs
                </a>
            </li> 
        </ul>
        <!-- searchbox-->
        <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
        <!-- ./searchbox-->
        <ul class="nav navbar-nav navbar-right"> 
            <li class=""> 
                <a href="{% url 'music:index' %}"> 
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Add album
                </a>
            </li> 
            <li class=""> 
                <a href="#"> 
                    <span class="glyphicon glyphicon-off" aria-hidden="true"> </span> Logout
                </a>
            </li> 
        </ul>
    </div>
    <!-- ./items --> 
  </div>
</nav>
<!-- ./nav --> 
{% block body %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

music/templates/details.html
{% extends 'base.html' %}
{% block title %} Music details {% endblock %}

{% block body %}
<div class="container">
  <img src="{{ album.album_logo }}">
  <h1> {{ album.album_title }}</h1>
  <h3> {{ album.artist }}</h3>

  <form action="{% url 'music:favorite' album.id %}" method="POST">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id}}"> 
      <label for="song{{forloop.counter}}">
        {{ song.song_title}}
        {% if song.favorite %}
          <img src="http://i.imgur.com/b9b13Rd.png" />
        {% endif %}
      </label><br>
    {% endfor %}
    <input type="submit" name="enviar">
  </form>
</div>
{% endblock %}

music/templates/index.html
<!-- main --> 
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h2>Here are all my albums:</h2>
  	{% if all_albums %}
		<ul class="list-group">
			{% for album in all_albums %}
			<li class="list-group-item">
				<a href="{% url 'music:detail' album.id %}"> {{album.artist}}</a>
			</li>
			{% endfor %}
		</ul>
	{% else %}
		<h3> You don't have albums </h3>
	{% endif %}
</div>
{% endblock %}

<!-- ./main --> 